In [1]:
import tensorflow as tf

In [2]:
print (tf.__version__)

1.13.1


In [9]:
hello = tf.constant('hello')
world = tf.constant('world')
print (type(hello))

result = hello+world
print (result)

with tf.Session() as sess:
    result = sess.run(hello+world)
    print (result)

<class 'tensorflow.python.framework.ops.Tensor'>
Tensor("add_4:0", shape=(), dtype=string)
b'helloworld'


In [8]:
a = tf.constant(10)
b = tf.constant(12)
with tf.Session() as sess:
    c = sess.run(a+b)
    print (c)

22


In [11]:
import numpy as np
a = np.array([1,2])
b = np.array([2,3])
with tf.Session() as sess:
    c = sess.run(tf.add(a,b))
    print (c)

[3 5]


In [15]:
import numpy as np
a = np.array([1,2])
b = np.array([2,3])
with tf.Session() as sess:
    c = sess.run(tf.multiply(a,b))
    print (c)

[2 6]


In [17]:
import numpy as np
a = np.array([1,2])
b = np.array([2,3])
with tf.Session() as sess:
    c = sess.run(tf.multiply(a,b))
    print (c)

[2 6]


In [22]:
a = tf.fill((4,4), 1)
b = tf.fill((4,3,),2)
with tf.Session() as sess:
    c = sess.run(tf.matmul(a,b))
    print (type(c))
    print (c)

<class 'numpy.ndarray'>
[[8 8 8]
 [8 8 8]
 [8 8 8]
 [8 8 8]]
